- name: "Install Minio"
  hosts: minio-server
  become: true
  gather_facts: true
  roles:
    - minio
    - nginx
  vars:
    minio_server_release: "{{ minio_server_release_full }}"
    minio_client_release: "{{ minio_client_release_full }}"
    domains:
      - domain: "{{ minio_server_domain }}"
        service_port: "{{ minio_server_port }}"
      - domain: "{{ minio_console_domain }}"
        service_port: "{{ minio_console_port }}"
